add firmware_version_table for sensor contorl UI feature
Proko-Tech/proko-park-be pull request #51
Opened 2022-07-10 05:16 UTC by hage1005

# Administrative Info
Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes
What changes did you make?
- add a migration file to add firmware version table

## Checklist

Remove any items which are not applicable.

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tested my program thoroughly
- [ ] Did you add/sub fields in the environment file? if so please update .env_sample

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

2022-07-10 18:54 UTC, mingkaili requested changes

2022-07-10 18:54 UTC, mingkaili commented on database/migrations/20220702225402_firmware_version_table.js
> +    return knex.schema.createTable('firmware_version', (tbl)=>{
nit: firmware_versions

2022-07-10 18:54 UTC, mingkaili commented on database/migrations/20220702225402_firmware_version_table.js
> +        tbl.string('version').primary().notNullable();
This is should not be the primary key. When designing a table, primary key should follow the below practices:
1. Primary keys should be as small as necessary. Prefer a numeric type because numeric types are stored in a much more compact format than character formats. This is because most primary keys will be foreign keys in another table as well as used in multiple indexes. The smaller your key, the smaller the index, the less pages in the cache you will use.
2. Primary keys should never change. Updating a primary key should always be out of the question. This is because it is most likely to be used in multiple indexes and used as a foreign key. Updating a single primary key could cause of ripple effect of changes.
3. Do NOT use "your problem primary key" as your logic model primary key. For example passport number, social security number, or employee contract number as these "natural keys" can change in real world situations. Make sure to add UNIQUE constraints for these where necessary to enforce consistency.

Having a string and version being the primary key violates the above 3 rules. Use a numeric primary key as we always do to be consistent, and the version can just be a simple field.

2022-07-10 22:29 UTC, hage1005 commented on database/migrations/20220702225402_firmware_version_table.js
> +        tbl.string('version').primary().notNullable();
Wasn't aware these principa, fixed

2022-07-11 03:28 UTC, hage1005 commented on database/migrations/20220702225402_firmware_version_table.js
> +        tbl.increments('id').primary();
Does primary already implies not null and unique?

2022-07-11 03:37 UTC, mingkaili commented on database/migrations/20220702225402_firmware_version_table.js
> +        tbl.increments('id').primary();
I think primary actually implies unique, but in a normal sql query to create a table we always add NOT NULL in the primary key. I tried digging around the knex documentation, but they have very limited information about the primary function. 

The formal definition of PRIMARY KEY is: 

PRIMARY KEY | A constraint that uniquely identifies each record in a database table
-- | --

2022-07-11 05:07 UTC, mingkaili requested changes
Also, for small fixes like this, no need to make a new commit. Use the command: `git commit --amend` in the future. I believe I have mentioned this in the other PR.

2022-07-11 05:07 UTC, mingkaili commented on database/migrations/20220702225402_firmware_version_table.js
> +        tbl.text('ESP8266_url').notNullable();
Sorry I didn't notice this earlier. All of our fields in database are lowercase, let's keep that convention.

2022-07-11 19:21 UTC, hage1005 commented
I can do amend locally. Since the previous commit is already pushed, do you want me to force push after amend?

2022-07-11 19:38 UTC, mingkaili commented
> I can do amend locally. Since the previous commit is already pushed, do you want me to force push after amend?

no worries for this PR. We can squash and merge it instead.

2022-07-11 20:11 UTC, hage1005 commented on database/migrations/20220702225402_firmware_version_table.js
> +        tbl.text('ESP8266_url').notNullable();
updated

2022-07-11 22:18 UTC, mingkaili approved these changes
LGTM

2022-07-11 23:04 UTC, merged