feature/create-deletion-route
Proko-Tech/proko-park-be pull request #65
Opened 2022-09-15 01:26 UTC by RyanHUNGry

# Administrative Info

Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes

What changes did you make?

Bundled 4 actions into one large route for account deletion:
1. Deletion of every vehicle ownership record the user has (vehicle ownership table)
2. Deletion of every primary vehicle record the user specifies (vehicles table)
3. Reassignment of primary vehicle ownership the user specifies (vehicle ownership table)
4. Deletion of user information (Users table)

## Checklist

Remove any items which are not applicable.

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have added tested my program thoroughly
- 
### Confirmation of Change

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| ----------------------- |
| [TODO Screenshot Link]  |

2022-09-15 17:55 UTC, mingkaili requested changes

2022-09-15 17:55 UTC, mingkaili commented on app/routes/api/users/index.js
> +                if (index !== -1) {
For readability, we want to avoid nesting as much as possible. For instance, we can avoid using the else here by using the return keyword(return in forEach callback is the equivalent of continue in a for loop).

```
if (index !== -1) {
    updateList.push({
        user_id: ownershipAndUsers[index].user_id,
        vehicle_id: ownershipAndUsers[index].vehicle_id});
    return;
}
const convertedEmailIndex = ownershipAndUsers.findIndex(
    (row) => row.email === action.reassigned_user,
)
insertList.push({
    vehicle_id: action.vehicle.id,
    is_primary_owner: 1,
    status: 'ACCEPTED',
    user_id: ownershipAndUsers[index].id});
```

2022-09-15 17:55 UTC, mingkaili commented on app/routes/api/users/index.js
> +                    const convertedEmailIndex = ownershipAndUsers.findIndex(
I don't think you need to do this again. `index` should be what you are looking for. Also, you need to query email and vehicle id bc there can be multiple rows with the same user.

2022-09-15 17:55 UTC, mingkaili commented on app/routes/api/users/index.js
> +                        user_id: ownershipAndUsers[convertedEmailIndex].id});
ditto, 
1. `index` should be sufficient, 
2. and I believe you should use `ownershipAndUsers[convertedEmailIndex].user_id`

2022-09-15 17:55 UTC, mingkaili commented on app/routes/api/users/index.js
> +            await vehicleOwnershipModel.batchInsertTransferOwnership(
This function only has one parameter, how come you are passing 2?

2022-09-15 17:55 UTC, mingkaili commented on database/models/vehicleOwnershipModel.js
> +async function batchUpdateTransferOwnership(row) {
Rename this to `updateByUserIdAndVehicleId`

2022-09-15 17:55 UTC, mingkaili commented on database/models/vehicleOwnershipModel.js
> +    await db('vehicle_ownership').where({user_id: row.user_id, vehicle_id: row.vehicle_id}).update({is_primary_owner: 1, status: 'ACCEPTED'})
instead of hard coding `{is_primary_owner: 1, status: 'ACCEPTED'}`, use the parameter, and pass it as arguments

2022-09-15 17:55 UTC, mingkaili commented on app/routes/api/users/index.js
> +                    await vehicleOwnershipModel.batchUpdateTransferOwnership(
not really a batch update here, as this function updates individual rows each time.

2022-09-15 17:55 UTC, mingkaili commented on database/models/vehicleOwnershipModel.js
> +async function batchInsertTransferOwnership(assignToUsers) {
Are you planning on using transactions or no?

2022-09-15 19:41 UTC, RyanHUNGry commented on app/routes/api/users/index.js
> +            await vehicleOwnershipModel.batchInsertTransferOwnership(
My bad. Original function took 2 but refactored just takes the row to insert.

2022-09-15 19:54 UTC, RyanHUNGry commented on app/routes/api/users/index.js
> +                        user_id: ownershipAndUsers[convertedEmailIndex].id});
2. I'm doing a left join where users is the left table and vehicle_ownership is the right. I'm joining on users.id and vehicle_ownership.user_id. Doing a left join makes it so that I still keep all user.id even if said user does not own a vehicle, which is important because I still need that information if the user tries to assign a vehicle to a person without any. Thus, I use user.id as opposed to vehicle_ownership.user_id for my user id.

2022-09-15 20:27 UTC, mingkaili commented on app/routes/api/users/index.js
> +                        user_id: ownershipAndUsers[convertedEmailIndex].id});
First of all, I am not sure about what you mean by: 

> Doing a left join makes it so that I still keep all user.id even if said user does not own a vehicle, which is important because I still need that information if the user tries to assign a vehicle to a person without any. 

I took a second look at this, and discovered the design you have is inefficient. 
1. You have users (the left join) as the first class citizen here, but it actually will make more sense to have the vehicle_ownership as the first class citizen. 
2. Plus, right now you are just querying every single result in the table which will return a huge list at scale. Instead, you can pass a `WHERE clause` for querying all records with a list of `vehicle_id` which will return a massively smaller set of records (that will serve the same purpose for your code). 
3. Having the above record, you will see all existing ownership records for vehicles 1, 2, 3..., and then you can search if the action exists in the record(exists: goes into update list, otherwise, goes into insert list).

Lastly, it's a bad practice to do something such as:
`user_id: ownershipAndUsers[convertedEmailIndex].id` reasons being:
1. When devs read your code, `ownershipAndUsers[convertedEmailIndex].id` translates to: we are getting the `id` from an item in a list of `ownershipAndUser` records. Meaning: `id` is for `ownershipAndUser`, but instead, it represents `user_id`. 
2. It's a bad practice to make `id`(a general key) representing another entity.

2022-09-15 20:32 UTC, RyanHUNGry commented on app/routes/api/users/index.js
> +                    const convertedEmailIndex = ownershipAndUsers.findIndex(
Currently, the index variable only stores an index if the person I'm assigning the vehicle to is a co-owner. If the person is not a co-owner, then I need to search, in my joined table, a row where the email matches so that I can extract users.id. Even if the person has multiple rows, I just get the index of the first matching row, which gives me my user id. Thus, which row I gather the user ID from doesn't matter.

2022-09-15 20:33 UTC, mingkaili requested changes

2022-09-15 20:33 UTC, mingkaili commented on app/routes/api/users/index.js
> +            const ownershipAndUsers = await vehicleOwnershipModel.getOwnershipJoinUser();
You are getting every single user record joining their vehicle_ownership record here(This is going to be a huge list). Instead, make `vehicle_ownership` the first class citizen and pass in the list of `vehicle_ids`.

2022-09-15 20:33 UTC, mingkaili commented on database/models/vehicleOwnershipModel.js
> +    const result = await db('users')
`SELECT * FROM vehicle_ownership join users on vehicle_ownership.user_id = users.id WHERE vehicle_ownership.vehicle_id in (vehicle_id1, vehicle_id2, etc);
` No need to do left join here bc `vehicle_ownership` is the first class citizen.

2022-09-15 20:37 UTC, mingkaili commented on app/routes/api/users/index.js
> +                    const convertedEmailIndex = ownershipAndUsers.findIndex(
That's right, I was under the impression you had vehicle_ownership as the first class citizen(which will be a better design), but instead you had users. Read over my comment here: https://github.com/Proko-Tech/proko-park-be/pull/65#discussion_r972387160

2022-09-15 20:47 UTC, RyanHUNGry commented on app/routes/api/users/index.js
> +                        user_id: ownershipAndUsers[convertedEmailIndex].id});
Okay gotcha. I'll get started on implementing this. Sorry about the confusion.

2022-09-15 23:35 UTC, RyanHUNGry commented on database/models/vehicleOwnershipModel.js
> +async function batchInsertTransferOwnership(assignToUsers) {
Going to leave the transaction as a feature to be picked up for now.

2022-09-15 23:42 UTC, RyanHUNGry commented on app/routes/api/users/index.js
> +                    array[index].user_id = newOwnerIds[indexOfUserId].id
I know you specified that using .id isn't good convention. However, because I am searching for email matches in the Users row, the user id is named id. Would this be okay? Or do I need to rename the object field in newOwnerIds to user_id?

2022-09-16 20:28 UTC, mingkaili commented on app/routes/api/users/index.js
> +                    array[index].user_id = newOwnerIds[indexOfUserId].id
This is ok bc `newOwnerIds` is essentially indicating `user_id`.

2022-09-16 20:28 UTC, mingkaili approved these changes

2022-09-16 20:53 UTC, merged